project: 
  type: book
  output-dir: _book
  
book:
  title: "UNH Biological Sciences Graduate Program"
  date: last-modified 
  description: "This is the manual for the graduate programs in the Department of Biological Sciences at the University of New Hampshire." 
  
  page-footer:
    left: |
      <a href="https://colsa.unh.edu/biological-sciences/">UNH Biological Sciences</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://quantmarineecolab.github.io/dbs-grad-programs/
  repo-url: https://github.com/QuantMarineEcoLab/dbs-grad-programs
  repo-actions: [edit,issue]

  chapters: 
    - index.qmd
    - 01-program-overview.qmd
    - 02-admissions.qmd
    - 03-onboarding.qmd
    - 04-mentorship.qmd
    - 05-ms-marinebiology.qmd
    - 06-phd-marinebiology.qmd
    - 07-ms-integrativebiology.qmd
    - 08-phd-integrativebiology.qmd
    - 09-ms-neurosciencebehavior.qmd
    - 10-phd-neurosciencebehavior.qmd
    - 11-courses.qmd
    - 12-funding.qmd
    - 13-finishing.qmd
    - 14-UNH-and-Durham.qmd
    - 15-helpful-links.qmd



# not sure what the following line does; those files are present
bibliography: [references.bib, book.bib]

