project: 
  type: book
  output-dir: _book
  
book:
  title: "UNH Biological Sciences Graduate Program"
  date: last-modified 
  description: "This is the manual for the graduate programs in the Department of Biological Sciences at the University of New Hampshire." 
  
  page-footer:
    left: |
      <a href="https://colsa.unh.edu/biological-sciences/">UNH Biological Sciences</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://quantmarineecolab.github.io/dbs-grad-programs/
  repo-url: https://github.com/QuantMarineEcoLab/dbs-grad-programs
  repo-actions: [edit,issue]

  chapters: 
    - index.qmd
    - 01-program-overview.qmd
    - 02-admissions.qmd
    - 03-onboarding.qmd
    - 04-ms-marinebiology.qmd
    - 05-phd-marinebiology.qmd
    - 06-ms-integrativebiology.qmd
    - 07-phd-integrativebiology.qmd
    - 08-ms-neurosciencebehavior.qmd
    - 09-phd-neurosciencebehavior.qmd
    - 10-funding.qmd
    - 11-finishing.qmd
    - 12-UNH-and-Durham.qmd
    - 13-helpful-links.qmd



# not sure what the following line does; those files are present
bibliography: [references.bib, book.bib]

